name: "Set Issue Label and Assignee"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        if: github.event.pull_request.user.login == 'pahud' && contains(github.event.pull_request.title, 'upgrade projen')
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          title-or-body: "title"
          parameters: >
            [
            {"keywords":["upgrade projen"],"labels":["projen/upgrade", "auto-merge"],"assignees":["pahud"]}
            ]
      - uses: Naturalclar/issue-action@v2.0.2
        if: github.event.pull_request.user.login == 'cdk-automation' && contains(github.event.pull_request.title, 'yarn upgrade')
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          #github-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          title-or-body: "title"
          parameters: >
            [
            {"keywords":["yarn upgrade"],"labels":["yarn/upgrade", "auto-merge"],"assignees":["pahud"]}
            ]
